name: OIDC Token Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # work around race condition.  Not needed if you have other work like checking out the repo.
      - run: sleep 5
      - run: |
          cat ~/.docker/config.json
          docker pull postgres
      - name: Get ID Token
        run: |
           
           IDTOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
           echo $IDTOKEN
           jwtd() {
             if [[ -x $(command -v jq) ]]; then
                  jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                  echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
             fi
           }
           jwtd $IDTOKEN

  reuse:
    uses: patterson-io/reusable-workflow/.github/workflows/s3-upload.yml@main
